Added Dropdown and "tried" to implement translation
SevaSk/ecoute pull request #21
Opened 2023-05-23 23:47 UTC by Adarsha-gg

I created the dropbox it can be edited to add new languages. I also added the preffered_language variable so that the value of the dropbox goes to the class so it can be accessed but I couldn't find a way to actually translate the transcript in real time. This is same as the last pull request I closed with the only change being the whisper's model.

2023-05-24 00:09 UTC, SevaSk commented on AudioTranscriber.py
> +    def __init__(self, mic_source, speaker_source,language):
minor: space after the comma

2023-05-24 00:09 UTC, SevaSk commented on AudioTranscriber.py
> +        self.preffered_language = language
the preffered_language memeber is set but never used

2023-05-24 00:10 UTC, SevaSk commented on AudioTranscriber.py
> +        self.audio_model = whisper.load_model(os.path.join(os.getcwd(), 'tiny'))
tiny.en.pt file exists in the root directory but tiny does not exist so this will crash on this line

2023-05-24 00:12 UTC, SevaSk commented on AudioTranscriber.py
> +        result = self.audio_model.transcribe(file_path, fp16=torch.cuda.is_available(),task="translate")
We are not passing in the language which we want to transcribe. task="translate"  will translate the speech into English. which is not the flag we want

2023-05-24 00:12 UTC, SevaSk commented on main.py
> +    return transcript_textbox, response_textbox, update_interval_slider, update_interval_slider_label, freeze_button,combobox
minor: space after comma

2023-05-24 00:13 UTC, SevaSk commented on main.py
> +    global_transcriber = AudioTranscriber(user_audio_recorder.source, speaker_audio_recorder.source,combobox)
minor: space after comma

2023-05-24 00:14 UTC, SevaSk commented on AudioTranscriber.py
> +        self.audio_model = whisper.load_model(os.path.join(os.getcwd(), 'tiny'))
We also still want to use the tiny.en. model for English because of its better performance.

2023-05-24 00:15 UTC, SevaSk requested changes
Thanks for contributing! I cannot merge this PR yet I have left some comment with feedback.

2023-05-24 00:21 UTC, Adarsha-gg commented
Thank you for your feedback! I'll try implementing the changes. Also can
you tell me how to actually "translate" it to different languages I
couldn't find it in the whisper's documentation.

On Wed, 24 May 2023 at 06:00, Seva ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for contributing! I cannot merge this PR yet I have left some
> comment with feedback.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SevaSk/ecoute/pull/21#pullrequestreview-1440760664>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU6WWIOTZFC2VEHATRU26KTXHVHKDANCNFSM6AAAAAAYMSGH4Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-24 00:28 UTC, SevaSk commented
Here is the whisper documentation
https://github.com/openai/whisper/blob/main/README.md

we would want to use the language flag so the line would look something like
self.audio_model.transcribe(file_path, fp16=torch.cuda.is_available(), language= "The ISO 2 Letter Language Codes")

2023-05-24 02:51 UTC, Adarsha-gg commented
Hey man I may be wrong but I think as of now whisper can only translate
from different languages to english and not from english to different
languages. I think the purpose of this PR is to perform the latter one
which seems impossible to me or I am just dumb enough to not make it work.

On Wed, 24 May 2023 at 06:13, Seva ***@***.***> wrote:

> Here is the whisper documentation
> https://github.com/openai/whisper/blob/main/README.md
>
> we would want to use the language flag so the line would look something
> like
> self.audio_model.transcribe(file_path, fp16=torch.cuda.is_available(),
> language= "The ISO 2 Letter Language Codes")
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SevaSk/ecoute/pull/21#issuecomment-1560292034>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU6WWIIVH55G42GMAG2WXR3XHVI3VANCNFSM6AAAAAAYMSGH4Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-25 00:08 UTC, SevaSk commented
Whisper can definitely transcribe other languages if you get the feature complete and fully working please feel free to open another pull request! I cant merge this one if the feature is not fully implemented.

2023-05-25 00:08 UTC, closed without merging